# Generated by Django 4.2.3 on 2023-07-17 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название', max_length=90)),
                ('text', models.TextField(help_text='Текст новости')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Время создания новости')),
                ('author', models.ForeignKey(help_text='Автор новости', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Время создания лайка')),
                ('author', models.ForeignKey(help_text='Автор лайка', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(help_text='Новость на котрую поставили лайк', on_delete=django.db.models.deletion.CASCADE, to='blog.news')),
            ],
            options={
                'verbose_name': 'Лайк',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст комментария', max_length=450)),
                ('time_create', models.DateTimeField(auto_now_add=True, help_text='Время создания комментария')),
                ('author', models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(help_text='Новость на которую оставили комментарий', on_delete=django.db.models.deletion.CASCADE, to='blog.news')),
            ],
            options={
                'verbose_name': 'Комментарий',
            },
        ),
    ]
